#!/usr/bin/env node
/**
 * One-command local stack:
 *   1. spin up a local Hardhat node (FHEVM mock baked in)
 *   2. wait for it to be reachable on :8545
 *   3. deploy TesseraID + ConfidentialTBill + ConfidentialUSDC
 *   4. sync ABIs into web/lib/abi
 *   5. write contract addresses + a funded local-deployer key into web/.env.local
 *   6. start the Next.js dev server
 *
 * The deployer signer key is the first Hardhat default account, which is
 * publicly known and only ever has value on a local chain. NEVER reuse it for
 * anything other than `localhost`.
 */
import { spawn } from "node:child_process";
import { setTimeout as wait } from "node:timers/promises";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import net from "node:net";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const CONTRACTS = resolve(ROOT, "contracts");
const WEB = resolve(ROOT, "web");
const ENV_LOCAL = resolve(WEB, ".env.local");

// First Hardhat default mnemonic — public, do not reuse.
const HARDHAT_DEFAULT_PK =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

const children = [];
const cleanup = () => {
  for (const c of children) {
    try {
      c.kill("SIGTERM");
    } catch {}
  }
};
process.on("SIGINT", () => {
  cleanup();
  process.exit(0);
});
process.on("SIGTERM", () => {
  cleanup();
  process.exit(0);
});
process.on("exit", cleanup);

function header(s) {
  process.stdout.write(`\n\x1b[1;33m▌ ${s}\x1b[0m\n`);
}
function log(s) {
  process.stdout.write(`\x1b[2m  ${s}\x1b[0m\n`);
}

async function isPortOpen(port, host = "127.0.0.1") {
  return new Promise((resolveP) => {
    const sock = new net.Socket();
    sock.setTimeout(500);
    sock.once("connect", () => {
      sock.destroy();
      resolveP(true);
    });
    sock.once("error", () => resolveP(false));
    sock.once("timeout", () => {
      sock.destroy();
      resolveP(false);
    });
    sock.connect(port, host);
  });
}

async function waitForPort(port, timeoutMs = 60_000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    if (await isPortOpen(port)) return;
    await wait(400);
  }
  throw new Error(`Timed out waiting for :${port}`);
}

function spawnLogged(name, cmd, args, opts = {}) {
  const child = spawn(cmd, args, {
    stdio: ["ignore", "pipe", "pipe"],
    ...opts,
  });
  child.stdout.on("data", (d) =>
    process.stdout.write(`\x1b[2m[${name}]\x1b[0m ${d.toString().trimEnd()}\n`),
  );
  child.stderr.on("data", (d) =>
    process.stderr.write(`\x1b[2m[${name}]\x1b[0m ${d.toString().trimEnd()}\n`),
  );
  children.push(child);
  return child;
}

function readDeployedAddress(name) {
  const p = resolve(CONTRACTS, "deployments", "localhost", `${name}.json`);
  if (!existsSync(p)) return null;
  const json = JSON.parse(readFileSync(p, "utf8"));
  return json.address;
}

function writeEnvLocal({ tesseraId, tbill, usdc }) {
  const lines = [
    "# Auto-generated by scripts/dev-local.mjs — overwritten on each run.",
    "# Do not commit. Edit .env.local.example for shared defaults.",
    "",
    "# Public (browser-visible)",
    "NEXT_PUBLIC_WEB3AUTH_CLIENT_ID=" +
      (process.env.NEXT_PUBLIC_WEB3AUTH_CLIENT_ID ?? ""),
    "NEXT_PUBLIC_SEPOLIA_RPC=http://127.0.0.1:8545",
    `NEXT_PUBLIC_TESSERA_ID_ADDRESS=${tesseraId}`,
    `NEXT_PUBLIC_TBILL_ADDRESS=${tbill}`,
    `NEXT_PUBLIC_USDC_ADDRESS=${usdc}`,
    "",
    "# Server-only",
    "SEPOLIA_RPC=http://127.0.0.1:8545",
    `TESSERA_DEPLOYER_PK=${HARDHAT_DEFAULT_PK}`,
    `TESSERA_ID_ADDRESS=${tesseraId}`,
    `TBILL_ADDRESS=${tbill}`,
    `USDC_ADDRESS=${usdc}`,
    "",
  ];
  mkdirSync(dirname(ENV_LOCAL), { recursive: true });
  writeEnvLocalIfChanged(ENV_LOCAL, lines.join("\n"));
}

function writeEnvLocalIfChanged(path, content) {
  let prev = "";
  if (existsSync(path)) prev = readFileSync(path, "utf8");
  if (prev !== content) {
    writeFileSync(path, content);
    log(`wrote ${path}`);
  } else {
    log(`up to date: ${path}`);
  }
}

async function runOnce(cmd, args, opts = {}) {
  return new Promise((resolveP, rejectP) => {
    const c = spawn(cmd, args, { stdio: "inherit", ...opts });
    c.on("exit", (code) => {
      if (code === 0) resolveP();
      else rejectP(new Error(`${cmd} ${args.join(" ")} → exit ${code}`));
    });
    c.on("error", rejectP);
  });
}

(async () => {
  header("1. starting local Hardhat node on :8545");
  const node = spawnLogged("hardhat", "npx", ["hardhat", "node"], { cwd: CONTRACTS });
  await waitForPort(8545, 60_000);
  log("node ready");

  header("2. deploying contracts to localhost");
  await runOnce("npx", ["hardhat", "deploy", "--network", "localhost"], { cwd: CONTRACTS });

  const tesseraId = readDeployedAddress("TesseraID");
  const tbill = readDeployedAddress("ConfidentialTBill");
  const usdc = readDeployedAddress("ConfidentialUSDC");
  if (!tesseraId || !tbill || !usdc) {
    throw new Error("deployment artifacts missing");
  }
  log(`TesseraID         ${tesseraId}`);
  log(`ConfidentialTBill ${tbill}`);
  log(`ConfidentialUSDC  ${usdc}`);

  header("3. syncing ABIs → web/lib/abi");
  await runOnce("npm", ["run", "sync-abis"], { cwd: CONTRACTS });

  header("4. writing web/.env.local");
  writeEnvLocal({ tesseraId, tbill, usdc });

  header("5. starting Next.js dev server on :3000");
  const next = spawnLogged("next", "npx", ["next", "dev"], { cwd: WEB });
  await new Promise((resolveP) => next.on("exit", resolveP));
  cleanup();
})().catch((err) => {
  console.error("\n\x1b[31m✗ dev-local failed:\x1b[0m", err.message);
  cleanup();
  process.exit(1);
});
